baseurl = "http://example.com/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "maria hugo site"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "alexurquhart@gmail.com"

	
	
	title = "MY NAME"
	subtitle = "MY HUGO BLOG"

		
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"
    
    [[params.navlinks]]
	name = "FORSIDE"
	url = "forside"
	

	[[params.navlinks]]
	name = "OM"
	url = "om"
	
	[[params.navlinks]]
	name = "KONTAKT"
	url = "kontakt"
	
	[[params.navlinks]]
	name = "PORTFOLIO"
	url = "portfolio/"
    
    [[params.navlinks]]
	name = "BLOG"
	url = "blog/"
    